### ISSUE TITLE
What are the differences in the three font families? 

### ISSUE THREAD

**Issue by kenmcd** [marcologous/Open-Sauce-Fonts#16]
Looking at the preview images and trying to figure-out how they are different. Nothing in the description mentions this either.  
Like the fonts.  
Just trying to understand.

**Comment by marcologous** [comment]
Hi @kenmcd, I have added those differences in the description. The differences—as the structure is the same for them all—rather the features of each are: Open Sauce Sans (has ink traps), Open Sauce One (no ink traps), and Open Sauce Two (rounded corners).

**Comment by kenmcd** [comment]
Thanks!

**Comment by Preshonyee** [comment]
I was just about to ask the same thing...
