### ISSUE TITLE
Norwegian support

### ISSUE THREAD

**Issue by sigurdhasle** [marcologous/Open-Sauce-Fonts#4]
Hello!
Open Sauce Sans claims to have support for Norwegian – but it hasn't! We have three special Norwegian letters – æ, ø and å. The ø and å are fine, but the æ looks like ae –  «Blåbærgrøt» looks like «Blåbaergrøt»! Nobody writes like this. 
Can you make proper æ*s, please?

**Comment by marcologous** [comment]
Hi @sigurdhasle apologies for this but the proper "ae" has been added already. Please re-download the fonts and reinstall. I appreciate your patience regarding this issue.

**Comment by sigurdhasle** [comment]
Excellent (except Open Sans One). Thank you very much!
